"use client";

import { useRouter } from "@tanstack/react-router";
import { AlertTriangle, ArrowRight } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { ThoughtLine } from "@/components/ui/thought-line";
import type { ProjectFeatureTree } from "@/db/schema";
import {
	GENERATION_STATUS_POLL_INTERVAL_MS,
	GUARD_WAIT_MS,
} from "@/lib/constants";
import { featureTreeSchema } from "@/lib/feature-tree";
import {
	isBackgroundGeneration,
	isStaleCompletedLoader,
	resolveInitialGenerating,
} from "@/lib/generation-recovery";
import { consumeSuppressAutoGen } from "@/lib/prompt-handoff";
import { useUIStore } from "@/store";
import { FeatureMapCanvas } from "./feature-map-canvas";
import { featureTreeHasContent } from "./feature-view";

interface FiturDetailProps {
	projectId: string;
	projectName: string;
	featureTree: ProjectFeatureTree | null;
	featuresStatus?: string | null;
	step?: string | null;
}

// Module-scope in-flight guard: StrictMode phantom unmount->remount aborts
// the first fetch but the remount fires a second generate before the server
// frees its claim — dedupe at module scope so both mounts share one
// generation per project instead of racing two.
const inFlightFiturProjects = new Map<string, AbortController>();

function releaseFiturGuard(projectId: string, owner: AbortController) {
	if (inFlightFiturProjects.get(projectId) === owner) {
		inFlightFiturProjects.delete(projectId);
	}
}

const IDLE_FITUR_TITLE = "AI sedang menyusun daftar fitur";

export function FiturDetail({
	projectId,
	projectName,
	featureTree,
	featuresStatus,
}: FiturDetailProps) {
	const router = useRouter();
	const showToast = useUIStore((s) => s.showToast);
	const [isGenerating, setIsGenerating] = useState(() =>
		resolveInitialGenerating(
			true,
			featuresStatus,
			featureTreeHasContent(featureTree),
		),
	);
	const [hasError, setHasError] = useState(false);
	const [localTree, setLocalTree] = useState<ProjectFeatureTree | null>(
		featureTree,
	);
	const isGeneratingRef = useRef(false);
	const abortRef = useRef<AbortController | null>(null);
	const hasAutoGenerated = useRef(false);

	useEffect(() => {
		if (featureTree && featureTreeHasContent(featureTree)) {
			setLocalTree(featureTree);
		}
	}, [featureTree]);

	useEffect(() => {
		const hasContent = featureTreeHasContent(featureTree ?? localTree);
		const staleCompleted = isStaleCompletedLoader(featuresStatus, hasContent);
		const siblingLive = inFlightFiturProjects.has(projectId) && !hasContent;
		const backgroundLive = isBackgroundGeneration(featuresStatus, hasContent);
		if (!staleCompleted && !backgroundLive && !siblingLive) return;
		let cancelled = false;
		if (staleCompleted) {
			void router.invalidate();
			return;
		}
		setIsGenerating(true);
		const timer = setInterval(() => {
			if (cancelled) return;
			void router.invalidate();
		}, GENERATION_STATUS_POLL_INTERVAL_MS);
		return () => {
			cancelled = true;
			clearInterval(timer);
		};
	}, [projectId, featuresStatus, featureTree, localTree, router]);

	useEffect(() => {
		if (featureTreeHasContent(featureTree ?? localTree)) {
			setIsGenerating(false);
			isGeneratingRef.current = false;
		}
	}, [featureTree, localTree]);

	const handleGenerate = useCallback(async () => {
		if (isGeneratingRef.current) return;
		if (inFlightFiturProjects.has(projectId)) {
			const deadline = Date.now() + GUARD_WAIT_MS;
			while (inFlightFiturProjects.has(projectId) && Date.now() < deadline) {
				await new Promise((r) => setTimeout(r, 50));
			}
			if (inFlightFiturProjects.has(projectId)) return;
		}
		isGeneratingRef.current = true;
		setIsGenerating(true);
		setHasError(false);

		abortRef.current?.abort();
		const controller = new AbortController();
		abortRef.current = controller;
		inFlightFiturProjects.set(projectId, controller);

		try {
			const response = await fetch("/api/features/generate", {
				method: "POST",
				headers: { "Content-Type": "application/json" },
				body: JSON.stringify({ projectId }),
				signal: controller.signal,
			});
			if (!response.ok) {
				if (response.status === 409) {
					releaseFiturGuard(projectId, controller);
					if (!inFlightFiturProjects.has(projectId)) {
						setHasError(true);
						showToast(
							"Sesi generate sebelumnya terputus. Generate ulang.",
							"error",
						);
					}
					isGeneratingRef.current = false;
					setIsGenerating(false);
					return;
				}
				if (response.status === 429) {
					showToast(
						"Terlalu banyak permintaan. Tunggu sebentar lalu coba lagi.",
						"error",
					);
					setHasError(true);
					isGeneratingRef.current = false;
					setIsGenerating(false);
					return;
				}
				const error = await response.json().catch(() => ({}));
				throw new Error(error.error || "Gagal generate daftar fitur");
			}
			const data = await response.json().catch(() => null);
			const rawTree: unknown =
				data && typeof data === "object" && "featureTree" in data
					? data.featureTree
					: null;
			const parsed = featureTreeSchema.safeParse(rawTree);
			if (parsed.success) {
				setLocalTree(parsed.data);
				showToast("Daftar fitur berhasil digenerate!", "success");
			}
			void router.invalidate();
		} catch (error: unknown) {
			if (error instanceof DOMException && error.name === "AbortError") {
				if (abortRef.current !== controller) {
					if (abortRef.current === null) {
						isGeneratingRef.current = false;
						setIsGenerating(false);
						setHasError(true);
					}
					return;
				}
				isGeneratingRef.current = false;
				setIsGenerating(false);
				return;
			}
			console.error("Generate fitur error:", error);
			showToast(
				error instanceof Error ? error.message : "Gagal generate daftar fitur",
				"error",
			);
			setHasError(true);
			isGeneratingRef.current = false;
			setIsGenerating(false);
			abortRef.current = null;
			return;
		} finally {
			releaseFiturGuard(projectId, controller);
		}
		isGeneratingRef.current = false;
		setIsGenerating(false);
		abortRef.current = null;
	}, [projectId, showToast, router]);

	const handleGenerateRef = useRef(handleGenerate);
	handleGenerateRef.current = handleGenerate;

	useEffect(() => {
		const hasContent = featureTreeHasContent(featureTree ?? localTree);
		if (
			hasContent ||
			featuresStatus === "completed" ||
			featuresStatus === "generating" ||
			hasAutoGenerated.current
		)
			return;
		if (consumeSuppressAutoGen(projectId)) return;
		hasAutoGenerated.current = true;
		handleGenerateRef.current();
	}, [featuresStatus, featureTree, localTree, projectId]);

	const previousProjectIdRef = useRef(projectId);
	useEffect(() => {
		if (
			previousProjectIdRef.current &&
			projectId &&
			previousProjectIdRef.current !== projectId
		) {
			const owner = abortRef.current;
			owner?.abort();
			abortRef.current = null;
			if (owner) releaseFiturGuard(previousProjectIdRef.current, owner);
			isGeneratingRef.current = false;
			hasAutoGenerated.current = false;
			setHasError(false);
			setLocalTree(null);
		}
		previousProjectIdRef.current = projectId;
	}, [projectId]);

	const displayTree = featureTreeHasContent(localTree)
		? localTree
		: featureTreeHasContent(featureTree)
			? featureTree
			: null;
	const hasContent = featureTreeHasContent(displayTree);

	return (
		<div className="flex h-full flex-col bg-onyx text-snow">
			<div className="flex items-center justify-between border-b border-graphite bg-obsidian px-4 py-3">
				<h1 className="truncate font-inter text-lg font-[510]">
					{isGenerating ? "AI sedang menyusun daftar fitur..." : projectName}
				</h1>
			</div>

			<div className="relative flex-1 overflow-hidden">
				{isGenerating && !hasContent ? (
					<div className="flex h-full flex-col">
						<div className="px-4 pt-3">
							<ThoughtLine
								working
								label={IDLE_FITUR_TITLE}
								doneLabel="Daftar fitur selesai"
							/>
						</div>
						<div className="relative min-h-0 flex-1">
							<FeatureMapCanvas productName={projectName} featureTree={null} />
						</div>
					</div>
				) : hasError && !hasContent ? (
					<div className="flex h-full flex-col items-center justify-center gap-3 p-8 text-center">
						<AlertTriangle size={40} className="text-crimson" />
						<h2 className="font-inter text-lg font-[510] text-snow">
							Gagal menyusun daftar fitur
						</h2>
						<p className="max-w-md text-sm text-fog">
							Terjadi kesalahan saat menghubungi AI. Daftar fitur belum
							tersimpan — tidak ada data yang hilang.
						</p>
						<button
							type="button"
							onClick={() => handleGenerate()}
							className="btn-primary rounded-md px-4 py-2 text-sm"
						>
							Coba Lagi
						</button>
					</div>
				) : !hasContent ? (
					<div className="flex h-full flex-col items-center justify-center gap-5 p-8 text-center">
						<div className="max-w-md">
							<h2 className="font-inter text-lg font-[510] text-snow">
								Belum ada daftar fitur
							</h2>
							<p className="mt-1 text-sm text-fog">
								Susun daftar fitur dari jawaban Anda sebelum lanjut ke PRD.
							</p>
						</div>
						<ol className="grid w-full max-w-2xl gap-3 text-left sm:grid-cols-3">
							{[
								{
									n: "1",
									t: "Jawab pertanyaan",
									d: "Lengkapi preferensi produk di tahap Ask.",
								},
								{
									n: "2",
									t: "Lihat Fitur",
									d: "AI menyusun fitur & subfitur di halaman ini.",
								},
								{
									n: "3",
									t: "Generate PRD",
									d: "Lanjut ke PRD 8 seksi dari daftar fitur.",
								},
							].map((s) => (
								<li
									key={s.n}
									className="rounded-xl border border-graphite bg-charcoal p-4"
								>
									<span
										aria-hidden
										className="flex h-6 w-6 items-center justify-center rounded-full border border-graphite bg-obsidian font-mono text-[11px] text-snow"
									>
										{s.n}
									</span>
									<p className="mt-2 text-sm font-[510] text-snow">{s.t}</p>
									<p className="mt-0.5 text-xs leading-relaxed text-fog">
										{s.d}
									</p>
								</li>
							))}
						</ol>
						<button
							type="button"
							onClick={() => handleGenerate()}
							className="btn-primary inline-flex items-center gap-1.5 rounded-md px-4 py-2 text-sm"
						>
							Susun Daftar Fitur
							<ArrowRight size={14} />
						</button>
					</div>
				) : (
					<FeatureMapCanvas
						productName={displayTree?.productName ?? projectName}
						featureTree={displayTree}
					/>
				)}
			</div>
		</div>
	);
}
